<?xml version="1.0" encoding="utf-8"?><Database Name="adbc" Class="ERNotationModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=adbc.stmartin.edu;Initial Catalog=adbc;User ID=adbcuser" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="adbcConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ERRelationship" Member="ERRelationships">
    <Type Name="ERRelationship" Id="ID2">
      <Column Name="ERRelationshipID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DescriptionShort" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DescriptionLong" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ERNotation" Member="ERNotations">
    <Type Name="ERNotation" Id="ID1">
      <Column Name="ERNotationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DescriptionShort" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DescriptionLong" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.SelectERNotations" Method="SelectERNotations">
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.SelectERRelationships" Method="SelectERRelationships">
    <ElementType IdRef="ID2" />
  </Function>
</Database>