#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADbC.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="adbc")]
	public partial class ModuleBaseModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertModule(Module instance);
    partial void UpdateModule(Module instance);
    partial void DeleteModule(Module instance);
    partial void InsertModuleIntroContent(ModuleIntroContent instance);
    partial void UpdateModuleIntroContent(ModuleIntroContent instance);
    partial void DeleteModuleIntroContent(ModuleIntroContent instance);
    partial void InsertModuleIntroSection(ModuleIntroSection instance);
    partial void UpdateModuleIntroSection(ModuleIntroSection instance);
    partial void DeleteModuleIntroSection(ModuleIntroSection instance);
    #endregion
		
		public ModuleBaseModelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["adbcConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModuleBaseModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModuleBaseModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModuleBaseModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModuleBaseModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Module> Modules
		{
			get
			{
				return this.GetTable<Module>();
			}
		}
		
		public System.Data.Linq.Table<ModuleIntroContent> ModuleIntroContents
		{
			get
			{
				return this.GetTable<ModuleIntroContent>();
			}
		}
		
		public System.Data.Linq.Table<ModuleIntroSection> ModuleIntroSections
		{
			get
			{
				return this.GetTable<ModuleIntroSection>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectModuleByName")]
		public ISingleResult<Module> SelectModuleByName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModuleName", DbType="VarChar(1)")] string moduleName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), moduleName);
			return ((ISingleResult<Module>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectModuleIntroSectionsByModuleID")]
		public ISingleResult<ModuleIntroSection> SelectModuleIntroSectionsByModuleID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModuleID", DbType="Int")] System.Nullable<int> moduleID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), moduleID);
			return ((ISingleResult<ModuleIntroSection>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectModuleIntroContentByModuleID")]
		public ISingleResult<ModuleIntroContent> SelectModuleIntroContentByModuleID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModuleID", DbType="Int")] System.Nullable<int> moduleID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), moduleID);
			return ((ISingleResult<ModuleIntroContent>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Module")]
	public partial class Module : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ModuleID;
		
		private string _ModuleName;
		
		private bool _HasIntroModal;
		
		private EntitySet<ModuleIntroSection> _ModuleIntroSections;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnModuleIDChanging(int value);
    partial void OnModuleIDChanged();
    partial void OnModuleNameChanging(string value);
    partial void OnModuleNameChanged();
    partial void OnHasIntroModalChanging(bool value);
    partial void OnHasIntroModalChanged();
    #endregion
		
		public Module()
		{
			this._ModuleIntroSections = new EntitySet<ModuleIntroSection>(new Action<ModuleIntroSection>(this.attach_ModuleIntroSections), new Action<ModuleIntroSection>(this.detach_ModuleIntroSections));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ModuleID
		{
			get
			{
				return this._ModuleID;
			}
			set
			{
				if ((this._ModuleID != value))
				{
					this.OnModuleIDChanging(value);
					this.SendPropertyChanging();
					this._ModuleID = value;
					this.SendPropertyChanged("ModuleID");
					this.OnModuleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ModuleName
		{
			get
			{
				return this._ModuleName;
			}
			set
			{
				if ((this._ModuleName != value))
				{
					this.OnModuleNameChanging(value);
					this.SendPropertyChanging();
					this._ModuleName = value;
					this.SendPropertyChanged("ModuleName");
					this.OnModuleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasIntroModal", DbType="Bit NOT NULL")]
		public bool HasIntroModal
		{
			get
			{
				return this._HasIntroModal;
			}
			set
			{
				if ((this._HasIntroModal != value))
				{
					this.OnHasIntroModalChanging(value);
					this.SendPropertyChanging();
					this._HasIntroModal = value;
					this.SendPropertyChanged("HasIntroModal");
					this.OnHasIntroModalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Module_ModuleIntroSection", Storage="_ModuleIntroSections", ThisKey="ModuleID", OtherKey="ModuleID")]
		public EntitySet<ModuleIntroSection> ModuleIntroSections
		{
			get
			{
				return this._ModuleIntroSections;
			}
			set
			{
				this._ModuleIntroSections.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ModuleIntroSections(ModuleIntroSection entity)
		{
			this.SendPropertyChanging();
			entity.Module = this;
		}
		
		private void detach_ModuleIntroSections(ModuleIntroSection entity)
		{
			this.SendPropertyChanging();
			entity.Module = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ModuleIntroContent")]
	public partial class ModuleIntroContent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ModuleIntroContentID;
		
		private int _ModuleIntroSectionID;
		
		private bool _IsImage;
		
		private string _Content;
		
		private int _ContentOrder;
		
		private EntityRef<ModuleIntroSection> _ModuleIntroSection;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnModuleIntroContentIDChanging(int value);
    partial void OnModuleIntroContentIDChanged();
    partial void OnModuleIntroSectionIDChanging(int value);
    partial void OnModuleIntroSectionIDChanged();
    partial void OnIsImageChanging(bool value);
    partial void OnIsImageChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnContentOrderChanging(int value);
    partial void OnContentOrderChanged();
    #endregion
		
		public ModuleIntroContent()
		{
			this._ModuleIntroSection = default(EntityRef<ModuleIntroSection>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleIntroContentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ModuleIntroContentID
		{
			get
			{
				return this._ModuleIntroContentID;
			}
			set
			{
				if ((this._ModuleIntroContentID != value))
				{
					this.OnModuleIntroContentIDChanging(value);
					this.SendPropertyChanging();
					this._ModuleIntroContentID = value;
					this.SendPropertyChanged("ModuleIntroContentID");
					this.OnModuleIntroContentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleIntroSectionID", DbType="Int NOT NULL")]
		public int ModuleIntroSectionID
		{
			get
			{
				return this._ModuleIntroSectionID;
			}
			set
			{
				if ((this._ModuleIntroSectionID != value))
				{
					if (this._ModuleIntroSection.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnModuleIntroSectionIDChanging(value);
					this.SendPropertyChanging();
					this._ModuleIntroSectionID = value;
					this.SendPropertyChanged("ModuleIntroSectionID");
					this.OnModuleIntroSectionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsImage", DbType="Bit NOT NULL")]
		public bool IsImage
		{
			get
			{
				return this._IsImage;
			}
			set
			{
				if ((this._IsImage != value))
				{
					this.OnIsImageChanging(value);
					this.SendPropertyChanging();
					this._IsImage = value;
					this.SendPropertyChanged("IsImage");
					this.OnIsImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this.OnContentChanging(value);
					this.SendPropertyChanging();
					this._Content = value;
					this.SendPropertyChanged("Content");
					this.OnContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContentOrder", DbType="Int NOT NULL")]
		public int ContentOrder
		{
			get
			{
				return this._ContentOrder;
			}
			set
			{
				if ((this._ContentOrder != value))
				{
					this.OnContentOrderChanging(value);
					this.SendPropertyChanging();
					this._ContentOrder = value;
					this.SendPropertyChanged("ContentOrder");
					this.OnContentOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ModuleIntroSection_ModuleIntroContent", Storage="_ModuleIntroSection", ThisKey="ModuleIntroSectionID", OtherKey="ModuleIntroSectionID", IsForeignKey=true)]
		public ModuleIntroSection ModuleIntroSection
		{
			get
			{
				return this._ModuleIntroSection.Entity;
			}
			set
			{
				ModuleIntroSection previousValue = this._ModuleIntroSection.Entity;
				if (((previousValue != value) 
							|| (this._ModuleIntroSection.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ModuleIntroSection.Entity = null;
						previousValue.ModuleIntroContents.Remove(this);
					}
					this._ModuleIntroSection.Entity = value;
					if ((value != null))
					{
						value.ModuleIntroContents.Add(this);
						this._ModuleIntroSectionID = value.ModuleIntroSectionID;
					}
					else
					{
						this._ModuleIntroSectionID = default(int);
					}
					this.SendPropertyChanged("ModuleIntroSection");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ModuleIntroSection")]
	public partial class ModuleIntroSection : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ModuleIntroSectionID;
		
		private int _ModuleID;
		
		private string _SectionTitle;
		
		private int _SectionOrder;
		
		private bool _OpenOnStart;
		
		private EntitySet<ModuleIntroContent> _ModuleIntroContents;
		
		private EntityRef<Module> _Module;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnModuleIntroSectionIDChanging(int value);
    partial void OnModuleIntroSectionIDChanged();
    partial void OnModuleIDChanging(int value);
    partial void OnModuleIDChanged();
    partial void OnSectionTitleChanging(string value);
    partial void OnSectionTitleChanged();
    partial void OnSectionOrderChanging(int value);
    partial void OnSectionOrderChanged();
    partial void OnOpenOnStartChanging(bool value);
    partial void OnOpenOnStartChanged();
    #endregion
		
		public ModuleIntroSection()
		{
			this._ModuleIntroContents = new EntitySet<ModuleIntroContent>(new Action<ModuleIntroContent>(this.attach_ModuleIntroContents), new Action<ModuleIntroContent>(this.detach_ModuleIntroContents));
			this._Module = default(EntityRef<Module>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleIntroSectionID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ModuleIntroSectionID
		{
			get
			{
				return this._ModuleIntroSectionID;
			}
			set
			{
				if ((this._ModuleIntroSectionID != value))
				{
					this.OnModuleIntroSectionIDChanging(value);
					this.SendPropertyChanging();
					this._ModuleIntroSectionID = value;
					this.SendPropertyChanged("ModuleIntroSectionID");
					this.OnModuleIntroSectionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleID", DbType="Int NOT NULL")]
		public int ModuleID
		{
			get
			{
				return this._ModuleID;
			}
			set
			{
				if ((this._ModuleID != value))
				{
					if (this._Module.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnModuleIDChanging(value);
					this.SendPropertyChanging();
					this._ModuleID = value;
					this.SendPropertyChanged("ModuleID");
					this.OnModuleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionTitle", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SectionTitle
		{
			get
			{
				return this._SectionTitle;
			}
			set
			{
				if ((this._SectionTitle != value))
				{
					this.OnSectionTitleChanging(value);
					this.SendPropertyChanging();
					this._SectionTitle = value;
					this.SendPropertyChanged("SectionTitle");
					this.OnSectionTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionOrder", DbType="Int NOT NULL")]
		public int SectionOrder
		{
			get
			{
				return this._SectionOrder;
			}
			set
			{
				if ((this._SectionOrder != value))
				{
					this.OnSectionOrderChanging(value);
					this.SendPropertyChanging();
					this._SectionOrder = value;
					this.SendPropertyChanged("SectionOrder");
					this.OnSectionOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpenOnStart", DbType="Bit NOT NULL")]
		public bool OpenOnStart
		{
			get
			{
				return this._OpenOnStart;
			}
			set
			{
				if ((this._OpenOnStart != value))
				{
					this.OnOpenOnStartChanging(value);
					this.SendPropertyChanging();
					this._OpenOnStart = value;
					this.SendPropertyChanged("OpenOnStart");
					this.OnOpenOnStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ModuleIntroSection_ModuleIntroContent", Storage="_ModuleIntroContents", ThisKey="ModuleIntroSectionID", OtherKey="ModuleIntroSectionID")]
		public EntitySet<ModuleIntroContent> ModuleIntroContents
		{
			get
			{
				return this._ModuleIntroContents;
			}
			set
			{
				this._ModuleIntroContents.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Module_ModuleIntroSection", Storage="_Module", ThisKey="ModuleID", OtherKey="ModuleID", IsForeignKey=true)]
		public Module Module
		{
			get
			{
				return this._Module.Entity;
			}
			set
			{
				Module previousValue = this._Module.Entity;
				if (((previousValue != value) 
							|| (this._Module.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Module.Entity = null;
						previousValue.ModuleIntroSections.Remove(this);
					}
					this._Module.Entity = value;
					if ((value != null))
					{
						value.ModuleIntroSections.Add(this);
						this._ModuleID = value.ModuleID;
					}
					else
					{
						this._ModuleID = default(int);
					}
					this.SendPropertyChanged("Module");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ModuleIntroContents(ModuleIntroContent entity)
		{
			this.SendPropertyChanging();
			entity.ModuleIntroSection = this;
		}
		
		private void detach_ModuleIntroContents(ModuleIntroContent entity)
		{
			this.SendPropertyChanging();
			entity.ModuleIntroSection = null;
		}
	}
}
#pragma warning restore 1591
